export interface PeriodicElement {
  symbol: string;
  name: string;
  period: number; // 1-7 main table, 8 lanthanides, 9 actinides
  group: number; // 1-18
}

const RAW: [string, string, number, number][] = [
  ["H", "Hydrogen", 1, 1],
  ["He", "Helium", 1, 18],
  ["Li", "Lithium", 2, 1],
  ["Be", "Beryllium", 2, 2],
  ["B", "Boron", 2, 13],
  ["C", "Carbon", 2, 14],
  ["N", "Nitrogen", 2, 15],
  ["O", "Oxygen", 2, 16],
  ["F", "Fluorine", 2, 17],
  ["Ne", "Neon", 2, 18],
  ["Na", "Sodium", 3, 1],
  ["Mg", "Magnesium", 3, 2],
  ["Al", "Aluminum", 3, 13],
  ["Si", "Silicon", 3, 14],
  ["P", "Phosphorus", 3, 15],
  ["S", "Sulfur", 3, 16],
  ["Cl", "Chlorine", 3, 17],
  ["Ar", "Argon", 3, 18],
  ["K", "Potassium", 4, 1],
  ["Ca", "Calcium", 4, 2],
  ["Sc", "Scandium", 4, 3],
  ["Ti", "Titanium", 4, 4],
  ["V", "Vanadium", 4, 5],
  ["Cr", "Chromium", 4, 6],
  ["Mn", "Manganese", 4, 7],
  ["Fe", "Iron", 4, 8],
  ["Co", "Cobalt", 4, 9],
  ["Ni", "Nickel", 4, 10],
  ["Cu", "Copper", 4, 11],
  ["Zn", "Zinc", 4, 12],
  ["Ga", "Gallium", 4, 13],
  ["Ge", "Germanium", 4, 14],
  ["As", "Arsenic", 4, 15],
  ["Se", "Selenium", 4, 16],
  ["Br", "Bromine", 4, 17],
  ["Kr", "Krypton", 4, 18],
  ["Rb", "Rubidium", 5, 1],
  ["Sr", "Strontium", 5, 2],
  ["Y", "Yttrium", 5, 3],
  ["Zr", "Zirconium", 5, 4],
  ["Nb", "Niobium", 5, 5],
  ["Mo", "Molybdenum", 5, 6],
  ["Tc", "Technetium", 5, 7],
  ["Ru", "Ruthenium", 5, 8],
  ["Rh", "Rhodium", 5, 9],
  ["Pd", "Palladium", 5, 10],
  ["Ag", "Silver", 5, 11],
  ["Cd", "Cadmium", 5, 12],
  ["In", "Indium", 5, 13],
  ["Sn", "Tin", 5, 14],
  ["Sb", "Antimony", 5, 15],
  ["Te", "Tellurium", 5, 16],
  ["I", "Iodine", 5, 17],
  ["Xe", "Xenon", 5, 18],
  ["Cs", "Cesium", 6, 1],
  ["Ba", "Barium", 6, 2],
  ["*", "Lanthanides", 6, 3], // placeholder
  ["Hf", "Hafnium", 6, 4],
  ["Ta", "Tantalum", 6, 5],
  ["W", "Tungsten", 6, 6],
  ["Re", "Rhenium", 6, 7],
  ["Os", "Osmium", 6, 8],
  ["Ir", "Iridium", 6, 9],
  ["Pt", "Platinum", 6, 10],
  ["Au", "Gold", 6, 11],
  ["Hg", "Mercury", 6, 12],
  ["Tl", "Thallium", 6, 13],
  ["Pb", "Lead", 6, 14],
  ["Bi", "Bismuth", 6, 15],
  ["Po", "Polonium", 6, 16],
  ["At", "Astatine", 6, 17],
  ["Rn", "Radon", 6, 18],
  ["Fr", "Francium", 7, 1],
  ["Ra", "Radium", 7, 2],
  ["**", "Actinides", 7, 3], // placeholder
  ["Rf", "Rutherfordium", 7, 4],
  ["Db", "Dubnium", 7, 5],
  ["Sg", "Seaborgium", 7, 6],
  ["Bh", "Bohrium", 7, 7],
  ["Hs", "Hassium", 7, 8],
  ["Mt", "Meitnerium", 7, 9],
  ["Ds", "Darmstadtium", 7, 10],
  ["Rg", "Roentgenium", 7, 11],
  ["Cn", "Copernicium", 7, 12],
  ["Nh", "Nihonium", 7, 13],
  ["Fl", "Flerovium", 7, 14],
  ["Mc", "Moscovium", 7, 15],
  ["Lv", "Livermorium", 7, 16],
  ["Ts", "Tennessine", 7, 17],
  ["Og", "Oganesson", 7, 18],
  // Lanthanides — display row 8
  ["La", "Lanthanum", 8, 3],
  ["Ce", "Cerium", 8, 4],
  ["Pr", "Praseodymium", 8, 5],
  ["Nd", "Neodymium", 8, 6],
  ["Pm", "Promethium", 8, 7],
  ["Sm", "Samarium", 8, 8],
  ["Eu", "Europium", 8, 9],
  ["Gd", "Gadolinium", 8, 10],
  ["Tb", "Terbium", 8, 11],
  ["Dy", "Dysprosium", 8, 12],
  ["Ho", "Holmium", 8, 13],
  ["Er", "Erbium", 8, 14],
  ["Tm", "Thulium", 8, 15],
  ["Yb", "Ytterbium", 8, 16],
  ["Lu", "Lutetium", 8, 17],
  // Actinides — display row 9
  ["Ac", "Actinium", 9, 3],
  ["Th", "Thorium", 9, 4],
  ["Pa", "Protactinium", 9, 5],
  ["U", "Uranium", 9, 6],
  ["Np", "Neptunium", 9, 7],
  ["Pu", "Plutonium", 9, 8],
  ["Am", "Americium", 9, 9],
  ["Cm", "Curium", 9, 10],
  ["Bk", "Berkelium", 9, 11],
  ["Cf", "Californium", 9, 12],
  ["Es", "Einsteinium", 9, 13],
  ["Fm", "Fermium", 9, 14],
  ["Md", "Mendelevium", 9, 15],
  ["No", "Nobelium", 9, 16],
  ["Lr", "Lawrencium", 9, 17],
];

export const ELEMENTS: PeriodicElement[] = RAW.map(([symbol, name, period, group]) => ({
  symbol,
  name,
  period,
  group,
}));

export const ELEMENT_BY_SYMBOL: Record<string, PeriodicElement> = Object.fromEntries(
  ELEMENTS.map((e) => [e.symbol, e]),
);
